import {FormEvent,ReactNode,useEffect,useState} from 'react';
import {Activity,AlertTriangle,Beaker,Database,Factory,FlaskConical,Leaf,RefreshCw,ShieldCheck,Sparkles} from 'lucide-react';
import {api} from './api';

type View='overview'|'optimize'|'predict'|'lots';
type Overview={rows:number;missing_cells:number;champion:string;metrics:{model:string;r2:number;mae_score:number;rmse_score:number}[];warning:string};
type Result={feasible:boolean;prediction_score:number;material_cost_index:number;settings:Record<string,number>;unmet_constraints:string[];notice:string};
const labels:Record<string,string>={cabbage_pct:'배추',radish_pct:'무',seasoning_pct:'양념',salt_pct:'소금',brine_salinity_pct:'절임수 염도',brining_hours:'절임 시간',fermentation_temp_c:'숙성 온도',fermentation_hours:'숙성 시간',storage_temp_c:'저장 온도'};
const unit=(key:string)=>key.includes('pct')?'%':key.includes('temp')?'°C':key.includes('hours')?'시간':'';

export default function App(){
 const [view,setView]=useState<View>('overview'); const [overview,setOverview]=useState<Overview|null>(null); const [error,setError]=useState('');
 useEffect(()=>{api<Overview>('/api/ml/overview').then(setOverview).catch(e=>setError(e.message))},[]);
 const title={overview:'김치 생산 인텔리전스',optimize:'배합·숙성 최적화',predict:'LOT 품질 예측',lots:'김치 LOT 탐색'}[view];
 return <div className="shell"><aside><div className="brand"><div className="mark">꽃순</div><div><b>평창꽃순이김치</b><small>FERMENTATION INTELLIGENCE</small></div></div><nav>
  <Nav id="overview" icon={<Activity/>} text="운영 개요"/><Nav id="optimize" icon={<Sparkles/>} text="배합·숙성 최적화"/><Nav id="predict" icon={<FlaskConical/>} text="품질 예측"/><Nav id="lots" icon={<Database/>} text="LOT 데이터"/>
 </nav><div className="sideNote"><ShieldCheck/><div><b>품질 의사결정 지원</b><span>출하 판정은 품질 담당자가 승인합니다.</span></div></div></aside>
 <main><header><div><span className="eyebrow">KIMCHI PRODUCTION AI / DEMO</span><h1>{title}</h1></div><div className="live"><i/>모델 준비됨</div></header>
 {error&&<div className="error"><AlertTriangle/>{error}</div>}{view==='overview'&&<OverviewPage data={overview}/>} {view==='optimize'&&<Optimize/>}{view==='predict'&&<Predict/>}{view==='lots'&&<Lots/>}
 </main></div>;
 function Nav({id,icon,text}:{id:View;icon:ReactNode;text:string}){return <button className={view===id?'active':''} onClick={()=>setView(id)}>{icon}{text}</button>}
}

function OverviewPage({data}:{data:Overview|null}){if(!data)return <Loading/>;return <><div className="notice"><Beaker/><div><b>검증 전 데모 환경</b><span>{data.warning}</span></div></div><section className="stats"><Card label="학습 LOT" value={data.rows.toLocaleString()} unit="건"/><Card label="챔피언 모델" value={data.champion}/><Card label="결측 셀" value={data.missing_cells.toString()} unit="개"/></section><section className="panel"><div className="panelHead"><div><span className="kicker">MODEL BENCHMARK</span><h2>동일 홀드아웃 성능 비교</h2></div><span className="tag">선정 기준 · MAE</span></div><div className="metrics"><div className="metricHeader"><span>모델</span><span>R²</span><span>MAE</span><span>RMSE</span></div>{data.metrics.map((m,i)=><div className={'metricRow '+(i===0?'winner':'')} key={m.model}><b>{m.model}{i===0&&<em>CHAMPION</em>}</b><span>{m.r2}</span><span>{m.mae_score}점</span><span>{m.rmse_score}점</span></div>)}</div></section><section className="two"><div className="panel process"><span className="kicker">DECISION FLOW</span><h2>원료에서 품질 판단까지</h2><div className="flow"><div><Leaf/><b>LOT 수집</b><small>배합 · 절임 · 숙성</small></div><i>→</i><div><Activity/><b>모델 분석</b><small>품질점수 · 잔차 · 제약</small></div><i>→</i><div><ShieldCheck/><b>담당자 승인</b><small>관능 · 이화학 · 출하</small></div></div></div><div className="panel"><span className="kicker">DATA READINESS</span><h2>운영 전환 체크</h2><ul className="check"><li>승인 배합표·품질규격 연결</li><li>원료 단가·공급사 연결</li><li>실제 LOT 이력으로 재학습</li><li>모델 버전·감사 로그 적용</li></ul></div></section></>}

function Optimize(){const [form,setForm]=useState({target_score:80,max_material_cost:85,cabbage_origin:'평창',line:'K1'});const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{setResult(await api('/api/ml/optimize',{method:'POST',body:JSON.stringify(form)}))}finally{setBusy(false)}}return <div className="workspace"><form className="panel form" onSubmit={submit}><span className="kicker">CONSTRAINTS</span><h2>탐색 조건</h2><Field label="목표 관능 품질점수"><input type="number" value={form.target_score} min="65" max="95" step="0.5" onChange={e=>setForm({...form,target_score:+e.target.value})}/></Field><Field label="원재료비 지수 상한"><input type="number" value={form.max_material_cost} min="45" max="100" onChange={e=>setForm({...form,max_material_cost:+e.target.value})}/></Field><Field label="배추 산지"><select value={form.cabbage_origin} onChange={e=>setForm({...form,cabbage_origin:e.target.value})}><option>평창</option><option>강릉</option><option>기타계약</option></select></Field><Field label="생산 라인"><select value={form.line} onChange={e=>setForm({...form,line:e.target.value})}><option>K1</option><option>K2</option></select></Field><button className="primary" disabled={busy}>{busy?<><RefreshCw className="spin"/>탐색 중</>:<><Sparkles/>최적 후보 탐색</>}</button></form><div className="panel result">{!result?<div className="placeholder"><Sparkles/><h2>조건을 입력해 후보를 탐색하세요</h2><p>유효한 배합 3,500개를 생성하고 품질점수와 원재료비 제약을 함께 평가합니다.</p></div>:<><div className={'verdict '+(result.feasible?'good':'warn')}><span>{result.feasible?'제약 충족 후보':'가장 가까운 대안'}</span><strong>{result.prediction_score}<small> 점</small></strong><p>원재료비 지수 {result.material_cost_index}</p></div>{result.unmet_constraints.map(x=><div className="error" key={x}><AlertTriangle/>{x}</div>)}<div className="settings">{Object.entries(result.settings).map(([k,v])=><div key={k}><span>{labels[k]}</span><b>{v} {unit(k)}</b></div>)}</div><p className="fine">{result.notice}</p></>}</div></div>}

const initial={cabbage_pct:71,radish_pct:7,seasoning_pct:20,salt_pct:2,brine_salinity_pct:11.1,brining_hours:12,fermentation_temp_c:4.8,fermentation_hours:42,storage_temp_c:1,cabbage_origin:'평창',line:'K1'};
function Predict(){const [form,setForm]=useState(initial);const [result,setResult]=useState<any>(null);async function submit(e:FormEvent){e.preventDefault();setResult(await api('/api/quality/predict',{method:'POST',body:JSON.stringify(form)}))}return <div className="workspace"><form className="panel form" onSubmit={submit}><span className="kicker">SINGLE LOT</span><h2>배합·공정값 입력</h2><div className="compactFields">{Object.keys(labels).map(k=><Field key={k} label={labels[k]}><input type="number" step="0.1" value={(form as any)[k]} onChange={e=>setForm({...form,[k]:+e.target.value})}/></Field>)}</div><Field label="배추 산지 / 라인"><div className="inline"><select value={form.cabbage_origin} onChange={e=>setForm({...form,cabbage_origin:e.target.value})}><option>평창</option><option>강릉</option><option>기타계약</option></select><select value={form.line} onChange={e=>setForm({...form,line:e.target.value})}><option>K1</option><option>K2</option></select></div></Field><button className="primary"><Activity/>예측 실행</button></form><div className="panel result">{!result?<div className="placeholder"><FlaskConical/><h2>LOT 조건을 입력하세요</h2><p>예측값은 검사 결과가 아니며 승인된 품질 판정을 대체하지 않습니다.</p></div>:<><div className={'verdict '+(result.warnings.length?'warn':'good')}><span>{result.status}</span><strong>{result.prediction_score}<small> 점</small></strong><p>{result.model}</p></div>{result.warnings.map((x:string)=><div className="error" key={x}><AlertTriangle/>{x}</div>)}<p className="fine">{result.notice}</p></>}</div></div>}

function Lots(){const [data,setData]=useState<any>(null);const [search,setSearch]=useState('');useEffect(()=>{api('/api/data/records?limit=25&search='+encodeURIComponent(search)).then(setData)},[search]);return <section className="panel"><div className="panelHead"><div><span className="kicker">TRACEABILITY</span><h2>김치 생산 LOT</h2></div><input className="search" aria-label="LOT 검색" placeholder="LOT 검색" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="tableWrap"><table><thead><tr><th>LOT</th><th>생산일</th><th>배추 산지</th><th>라인</th><th>양념</th><th>절임수 염도</th><th>숙성 온도</th><th>품질점수</th></tr></thead><tbody>{data?.records.map((r:any)=><tr key={r.lot_id}><td><b>{r.lot_id}</b></td><td>{r.produced_at.slice(0,10)}</td><td><span className="tag">{r.cabbage_origin}</span></td><td>{r.line}</td><td>{r.seasoning_pct.toFixed(2)}%</td><td>{r.brine_salinity_pct?.toFixed(2)??'미확인'}%</td><td>{r.fermentation_temp_c?.toFixed(1)??'미확인'}°C</td><td><b>{r.sensory_score.toFixed(2)}점</b></td></tr>)}</tbody></table></div><p className="fine">총 {data?.total??0}건 중 최대 25건 표시 · 데모 LOT</p></section>}
function Card({label,value,unit}:{label:string;value:string;unit?:string}){return <div className="stat"><span>{label}</span><strong>{value}<small>{unit}</small></strong></div>}
function Field({label,children}:{label:string;children:any}){return <label><span>{label}</span>{children}</label>}
function Loading(){return <div className="loading"><RefreshCw className="spin"/>모델을 준비하고 있습니다.</div>}
